# Generated by Django 3.2.12 on 2023-03-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='img/', verbose_name='image_location')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
