# Generated by Django 3.2.12 on 2023-03-11 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
