# Generated by Django 3.2.12 on 2023-03-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0003_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='hacker/', verbose_name='image_location')),
            ],
            options={
                'ordering': ['code_id'],
            },
        ),
    ]
