# Generated by Django 3.2.12 on 2023-04-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
