# Generated by Django 3.2.12 on 2023-04-11 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0007_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['createtime'],
            },
        ),
    ]
