# Generated by Django 3.2.12 on 2023-05-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0011_auto_20230523_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='tid',
            field=models.IntegerField(default=0),
        ),
    ]
