# Generated by Django 3.2.12 on 2023-05-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0012_timer_tid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('TimeStamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['TimeStamp'],
            },
        ),
    ]
