# Generated by Django 3.2.12 on 2023-05-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0014_post_pic_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['createtime']},
        ),
    ]
