# Generated by Django 3.2.12 on 2023-05-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0015_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic_url',
            field=models.TextField(default='https://www.colopen-blog.com/image/images/2023/04/08/003.jpg', max_length=100),
        ),
    ]
