# Generated by Django 3.2.12 on 2023-06-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0017_auto_20230601_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-createtime']},
        ),
    ]
