# Generated by Django 3.2 on 2024-06-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0021_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic_url',
            field=models.TextField(default='', max_length=100),
        ),
    ]
