# Generated by Django 3.2 on 2024-09-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0022_auto_20240613_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='todolist',
            name='percent',
            field=models.CharField(default='0%', max_length=10),
        ),
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(default='默认标题', max_length=50),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
